apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: boutique
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: 133130235898.dkr.ecr.ap-south-2.amazonaws.com/product-service:bc6b426a4991ba501a2e36c7fa0f2c0020589b8a
          ports:
            - containerPort: 3003
          env:
            - name: NODE_ENV
              value: development
            - name: PORT
              value: "3003"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: boutique-secrets
                  key: PRODUCTS_DB_URL

---

apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: boutique
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
  type: ClusterIP
